### ISSUE TITLE
Cant use indicatorBuilder 

### ISSUE THREAD

**Issue by han2-n** [fluttercandies/flex_grid#1]
indicatorBuilder not mapping inside flex_grid code

**Comment by qiu198022** [comment]
yes i meet same problem. Hope the author add the indicatorBuild inside the flex_grid.dart line 312
              LoadingMoreSliverList<T>(
                SliverListConfig<T>(
                  sourceList: widget.source,
                  itemExtent: widget.highPerformance ? _cellStyle.height : null,
of the indicatorBuild.
inherit the indicatorBuild inside the _FlexGridState from his widget FlexGrid

**Comment by zmtzawqlp** [comment]
sorry miss this.

fix with https://github.com/fluttercandies/flex_grid/commit/d3181b1008ba5f99aaf3877c20a9735a84517b14
